# Generated by Django 5.0.6 on 2024-07-23 19:23

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Missa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "horario",
                    models.TimeField(
                        choices=[
                            (datetime.time(7, 0), "7:00"),
                            (datetime.time(9, 0), "9:00"),
                            (datetime.time(19, 0), "19:00"),
                        ]
                    ),
                ),
                (
                    "pessoas",
                    models.ManyToManyField(
                        related_name="missas", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
