# Generated by Django 5.0.6 on 2024-08-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuariocustomizado",
            old_name="is_special_user",
            new_name="escalado",
        ),
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="additional_field_1",
        ),
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="additional_field_2",
        ),
    ]
