# Generated by Django 5.0.6 on 2024-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0002_rename_is_special_user_usuariocustomizado_escalado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="escalado",
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="enfermos",
            field=models.IntegerField(default=1),
        ),
    ]
