# Generated by Django 5.0.6 on 2024-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0003_remove_usuariocustomizado_escalado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="enfermos",
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="escalado",
            field=models.BooleanField(default=False),
        ),
    ]
