# Generated by Django 5.0.6 on 2024-08-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala", "0004_remove_usuariocustomizado_enfermos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocustomizado",
            name="escalado",
        ),
        migrations.AddField(
            model_name="usuariocustomizado",
            name="enfermos",
            field=models.IntegerField(
                default=0, verbose_name="Número de enfermos atendidos"
            ),
        ),
    ]
